# Configs for map generation.

GreenMapRules:
  # mountains
  mountain_percentage: 0.1

  # water bodies
  water_types:
    no water: 0.2
    river: 0.2
    sea side: 0.2
    lake: 0.2
    multiple: 0.2
  water_percentage: 0.1
  water_upper_limit: 0.5  # at most how much water can be in a map

  # vegies
  wood_percentage: 0.1
