starting_res:
  11: 1000
  21: 100
  22: 50
  23: 0

income_speed:
  11: [2, 4, 8, 12]
  21: [1, 2, 3, 4]
  22: [0, 2, 3, 4]
  23: [0, 1, 2, 3]

income_speed_std_pct:
  11: 0.25
  21: 0.25
  22: 0.25
  23: 0.25

food_consumption_per_pop: 2

mantainance_cost: 0
